version: 2.1
jobs:
  build_frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i --prefix frontend  
      - run: npm run lint --prefix frontend
      - persist_to_workspace:
          root: ~/
          paths:
            - project/frontend/node_modules
      - run: npm audit fix --prefix frontend  --force   
  build_backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i --prefix backend        
      - run: npm run lint --prefix backend 
      - persist_to_workspace:
          root: ~/
          paths:
            - project/backend/node_modules
      - run: npm audit fix --prefix backend    --force 
  test_frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: npm i --prefix frontend   
      - run: npm run test --prefix frontend
  test_backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: npm i --prefix backend     
      - run: npm run test --prefix backend      
workflows:
  default:
    jobs:
        - build_frontend
        - build_backend
        - test_frontend
        - test_backend